version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: archipelago
      POSTGRES_USER: archipelago_user
      POSTGRES_PASSWORD: 991112
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  archipelago-app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/archipelago
      SPRING_DATASOURCE_USERNAME: archipelago_user
      SPRING_DATASOURCE_PASSWORD: 991112
