package com.archipelago.catalog;

public enum CatalogErrorKind {
    INVALID_INPUT,
    UNSUPPORTED_PROVIDER_CAPABILITY,
    PROVIDER_UNAVAILABLE,
    RATE_LIMITED_RETRYABLE_EXTERNAL_FAILURE,
    PERMANENT_PROVIDER_DATA_ERROR,
    IMPORT_CONFLICT
}
